name: Telegram Daily Message

on:
  schedule:
    # Se ejecuta todos los días a las 09:00 AM UTC (que son las 05:00 AM hora local UTC-4 en tu huso horario actual)
    # Puedes cambiar '0 9 * * *' para ajustar la hora si lo deseas (minuto hora día_mes mes día_semana)
    - cron: '0 9 * * *'
  workflow_dispatch: # Permite ejecutar el flujo manualmente desde la interfaz de GitHub

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: node enviar-mensaje.js
