name: Telegram Daily Message

on:
  schedule:
    - cron: '5 10,19 * * *'
      timezone: 'America/Santiago'
  workflow_dispatch: # Permite ejecutar el flujo manualmente desde la interfaz de GitHub

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node enviar-mensaje.js
